name: GetCID_Engine
on:
  workflow_dispatch:
    inputs:
      iid:
        description: 'IID'
        required: true

jobs:
  activate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Axios
        run: npm install axios
      - name: Run
        run: node activate.js "${{ github.event.inputs.iid }}"
